//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let Chat = _ModuleRegistry.module("Chat");

    Slice.defineSequence(Chat, "AudioBytesHelper", "Ice.ByteHelper", true);

    Chat.CallChunk = class
    {
        constructor(from = "", to = "", seq = new Ice.Long(0, 0), data = null, timestamp = new Ice.Long(0, 0))
        {
            this.from = from;
            this.to = to;
            this.seq = seq;
            this.data = data;
            this.timestamp = timestamp;
        }

        _write(ostr)
        {
            ostr.writeString(this.from);
            ostr.writeString(this.to);
            ostr.writeLong(this.seq);
            Chat.AudioBytesHelper.write(ostr, this.data);
            ostr.writeLong(this.timestamp);
        }

        _read(istr)
        {
            this.from = istr.readString();
            this.to = istr.readString();
            this.seq = istr.readLong();
            this.data = Chat.AudioBytesHelper.read(istr);
            this.timestamp = istr.readLong();
        }

        static get minWireSize()
        {
            return  19;
        }
    };

    Slice.defineStruct(Chat.CallChunk, true, true);

    Chat.MessageDTO = class
    {
        constructor(from = "", to = "", group = "", message = "", timestamp = "", messageType = "", audio = null)
        {
            this.from = from;
            this.to = to;
            this.group = group;
            this.message = message;
            this.timestamp = timestamp;
            this.messageType = messageType;
            this.audio = audio;
        }

        _write(ostr)
        {
            ostr.writeString(this.from);
            ostr.writeString(this.to);
            ostr.writeString(this.group);
            ostr.writeString(this.message);
            ostr.writeString(this.timestamp);
            ostr.writeString(this.messageType);
            Chat.AudioBytesHelper.write(ostr, this.audio);
        }

        _read(istr)
        {
            this.from = istr.readString();
            this.to = istr.readString();
            this.group = istr.readString();
            this.message = istr.readString();
            this.timestamp = istr.readString();
            this.messageType = istr.readString();
            this.audio = Chat.AudioBytesHelper.read(istr);
        }

        static get minWireSize()
        {
            return  7;
        }
    };

    Slice.defineStruct(Chat.MessageDTO, true, true);

    Chat.UserDTO = class
    {
        constructor(username = "", online = false)
        {
            this.username = username;
            this.online = online;
        }

        _write(ostr)
        {
            ostr.writeString(this.username);
            ostr.writeBool(this.online);
        }

        _read(istr)
        {
            this.username = istr.readString();
            this.online = istr.readBool();
        }

        static get minWireSize()
        {
            return  2;
        }
    };

    Slice.defineStruct(Chat.UserDTO, true, true);

    Chat.GroupDTO = class
    {
        constructor(name = "", description = "")
        {
            this.name = name;
            this.description = description;
        }

        _write(ostr)
        {
            ostr.writeString(this.name);
            ostr.writeString(this.description);
        }

        _read(istr)
        {
            this.name = istr.readString();
            this.description = istr.readString();
        }

        static get minWireSize()
        {
            return  2;
        }
    };

    Slice.defineStruct(Chat.GroupDTO, true, true);

    Slice.defineSequence(Chat, "MessageListHelper", "Chat.MessageDTO", false);

    Slice.defineSequence(Chat, "UserListHelper", "Chat.UserDTO", false);

    Slice.defineSequence(Chat, "GroupListHelper", "Chat.GroupDTO", false);

    const iceC_Chat_ChatService_ids = [
        "::Chat::ChatService",
        "::Ice::Object"
    ];

    Chat.ChatService = class extends Ice.Object
    {
    };

    Chat.ChatServicePrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Chat.ChatService, Chat.ChatServicePrx, iceC_Chat_ChatService_ids, 0,
    {
        "createGroup": [, , , , [1], [[7], [7]], , , , ],
        "joinGroup": [, , , , [1], [[7], [7]], , , , ],
        "getGroups": [, , , , ["Chat.GroupListHelper"], , , , , ],
        "sendMessage": [, , , , [1], [[7], [7], [7]], , , , ],
        "sendGroupMessage": [, , , , [1], [[7], [7], [7]], , , , ],
        "getHistory": [, , , , ["Chat.MessageListHelper"], , , , , ],
        "getConnectedUsers": [, , , , ["Chat.UserListHelper"], , , , , ],
        "registerUser": [, , , , [1], [[7]], , , , ]
    });

    const iceC_Chat_Observer_ids = [
        "::Chat::Observer",
        "::Ice::Object"
    ];

    Chat.Observer = class extends Ice.Object
    {
    };

    Chat.ObserverPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Chat.Observer, Chat.ObserverPrx, iceC_Chat_Observer_ids, 0,
    {
        "notifyNewMessage": [, , , , , [[Chat.MessageDTO]], , , , ],
        "notifyUserConnected": [, , , , , [[7]], , , , ],
        "notifyUserDisconnected": [, , , , , [[7]], , , , ],
        "notifyGroupCreated": [, , , , , [[Chat.GroupDTO]], , , , ],
        "notifyCallChunk": [, , , , , [[Chat.CallChunk]], , , , ],
        "notifyCallStarted": [, , , , , [[7], [7]], , , , ],
        "notifyCallStopped": [, , , , , [[7], [7]], , , , ]
    });

    const iceC_Chat_Subject_ids = [
        "::Chat::Subject",
        "::Ice::Object"
    ];

    Chat.Subject = class extends Ice.Object
    {
    };

    Chat.SubjectPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Chat.Subject, Chat.SubjectPrx, iceC_Chat_Subject_ids, 0,
    {
        "attachObserver": [, , , , , [["Chat.ObserverPrx"]], , , , ],
        "detachObserver": [, , , , , [["Chat.ObserverPrx"]], , , , ]
    });

    const iceC_Chat_VoiceService_ids = [
        "::Chat::VoiceService",
        "::Ice::Object"
    ];

    Chat.VoiceService = class extends Ice.Object
    {
    };

    Chat.VoiceServicePrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Chat.VoiceService, Chat.VoiceServicePrx, iceC_Chat_VoiceService_ids, 0,
    {
        "sendVoiceNote": [, , , , [1], [[7], [7], [7], ["Chat.AudioBytesHelper"]], , , , ],
        "startCall": [, , , , , [[7], [7]], , , , ],
        "stopCall": [, , , , , [[7], [7]], , , , ],
        "sendCallChunk": [, , , , , [[Chat.CallChunk]], , , , ]
    });
    exports.Chat = Chat;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self.Ice._require : window.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self : window));
