//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public class MessageDTO implements java.lang.Cloneable,
                                   java.io.Serializable
{
    public String from;

    public String to;

    public String group;

    public String message;

    public String timestamp;

    public String messageType;

    public byte[] audio;

    public MessageDTO()
    {
        this.from = "";
        this.to = "";
        this.group = "";
        this.message = "";
        this.timestamp = "";
        this.messageType = "";
    }

    public MessageDTO(String from, String to, String group, String message, String timestamp, String messageType, byte[] audio)
    {
        this.from = from;
        this.to = to;
        this.group = group;
        this.message = message;
        this.timestamp = timestamp;
        this.messageType = messageType;
        this.audio = audio;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        MessageDTO r = null;
        if(rhs instanceof MessageDTO)
        {
            r = (MessageDTO)rhs;
        }

        if(r != null)
        {
            if(this.from != r.from)
            {
                if(this.from == null || r.from == null || !this.from.equals(r.from))
                {
                    return false;
                }
            }
            if(this.to != r.to)
            {
                if(this.to == null || r.to == null || !this.to.equals(r.to))
                {
                    return false;
                }
            }
            if(this.group != r.group)
            {
                if(this.group == null || r.group == null || !this.group.equals(r.group))
                {
                    return false;
                }
            }
            if(this.message != r.message)
            {
                if(this.message == null || r.message == null || !this.message.equals(r.message))
                {
                    return false;
                }
            }
            if(this.timestamp != r.timestamp)
            {
                if(this.timestamp == null || r.timestamp == null || !this.timestamp.equals(r.timestamp))
                {
                    return false;
                }
            }
            if(this.messageType != r.messageType)
            {
                if(this.messageType == null || r.messageType == null || !this.messageType.equals(r.messageType))
                {
                    return false;
                }
            }
            if(!java.util.Arrays.equals(this.audio, r.audio))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Chat::MessageDTO");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, from);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, to);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, group);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, message);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, timestamp);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, messageType);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, audio);
        return h_;
    }

    public MessageDTO clone()
    {
        MessageDTO c = null;
        try
        {
            c = (MessageDTO)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.from);
        ostr.writeString(this.to);
        ostr.writeString(this.group);
        ostr.writeString(this.message);
        ostr.writeString(this.timestamp);
        ostr.writeString(this.messageType);
        ostr.writeByteSeq(this.audio);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.from = istr.readString();
        this.to = istr.readString();
        this.group = istr.readString();
        this.message = istr.readString();
        this.timestamp = istr.readString();
        this.messageType = istr.readString();
        this.audio = istr.readByteSeq();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, MessageDTO v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public MessageDTO ice_read(com.zeroc.Ice.InputStream istr)
    {
        MessageDTO v = new MessageDTO();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<MessageDTO> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, MessageDTO v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<MessageDTO> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(MessageDTO.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final MessageDTO _nullMarshalValue = new MessageDTO();

    /** @hidden */
    public static final long serialVersionUID = -804051852L;
}
