//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public class CallChunk implements java.lang.Cloneable,
                                  java.io.Serializable
{
    public String from;

    public String to;

    public long seq;

    public byte[] data;

    public long timestamp;

    public CallChunk()
    {
        this.from = "";
        this.to = "";
    }

    public CallChunk(String from, String to, long seq, byte[] data, long timestamp)
    {
        this.from = from;
        this.to = to;
        this.seq = seq;
        this.data = data;
        this.timestamp = timestamp;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        CallChunk r = null;
        if(rhs instanceof CallChunk)
        {
            r = (CallChunk)rhs;
        }

        if(r != null)
        {
            if(this.from != r.from)
            {
                if(this.from == null || r.from == null || !this.from.equals(r.from))
                {
                    return false;
                }
            }
            if(this.to != r.to)
            {
                if(this.to == null || r.to == null || !this.to.equals(r.to))
                {
                    return false;
                }
            }
            if(this.seq != r.seq)
            {
                return false;
            }
            if(!java.util.Arrays.equals(this.data, r.data))
            {
                return false;
            }
            if(this.timestamp != r.timestamp)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Chat::CallChunk");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, from);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, to);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, seq);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, data);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, timestamp);
        return h_;
    }

    public CallChunk clone()
    {
        CallChunk c = null;
        try
        {
            c = (CallChunk)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.from);
        ostr.writeString(this.to);
        ostr.writeLong(this.seq);
        ostr.writeByteSeq(this.data);
        ostr.writeLong(this.timestamp);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.from = istr.readString();
        this.to = istr.readString();
        this.seq = istr.readLong();
        this.data = istr.readByteSeq();
        this.timestamp = istr.readLong();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, CallChunk v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public CallChunk ice_read(com.zeroc.Ice.InputStream istr)
    {
        CallChunk v = new CallChunk();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<CallChunk> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, CallChunk v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<CallChunk> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(CallChunk.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final CallChunk _nullMarshalValue = new CallChunk();

    /** @hidden */
    public static final long serialVersionUID = -695251457L;
}
