//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public interface ChatServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default boolean createGroup(String groupName, String creator)
    {
        return createGroup(groupName, creator, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean createGroup(String groupName, String creator, java.util.Map<String, String> context)
    {
        return _iceI_createGroupAsync(groupName, creator, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> createGroupAsync(String groupName, String creator)
    {
        return _iceI_createGroupAsync(groupName, creator, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> createGroupAsync(String groupName, String creator, java.util.Map<String, String> context)
    {
        return _iceI_createGroupAsync(groupName, creator, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupName -
     * @param iceP_creator -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_createGroupAsync(String iceP_groupName, String iceP_creator, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "createGroup", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_groupName);
                     ostr.writeString(iceP_creator);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean joinGroup(String groupName, String username)
    {
        return joinGroup(groupName, username, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean joinGroup(String groupName, String username, java.util.Map<String, String> context)
    {
        return _iceI_joinGroupAsync(groupName, username, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> joinGroupAsync(String groupName, String username)
    {
        return _iceI_joinGroupAsync(groupName, username, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> joinGroupAsync(String groupName, String username, java.util.Map<String, String> context)
    {
        return _iceI_joinGroupAsync(groupName, username, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupName -
     * @param iceP_username -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_joinGroupAsync(String iceP_groupName, String iceP_username, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "joinGroup", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_groupName);
                     ostr.writeString(iceP_username);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default GroupDTO[] getGroups()
    {
        return getGroups(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default GroupDTO[] getGroups(java.util.Map<String, String> context)
    {
        return _iceI_getGroupsAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<GroupDTO[]> getGroupsAsync()
    {
        return _iceI_getGroupsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<GroupDTO[]> getGroupsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getGroupsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<GroupDTO[]> _iceI_getGroupsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<GroupDTO[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getGroups", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     GroupDTO[] ret;
                     ret = GroupListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default boolean sendMessage(String from, String to, String message)
    {
        return sendMessage(from, to, message, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean sendMessage(String from, String to, String message, java.util.Map<String, String> context)
    {
        return _iceI_sendMessageAsync(from, to, message, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> sendMessageAsync(String from, String to, String message)
    {
        return _iceI_sendMessageAsync(from, to, message, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> sendMessageAsync(String from, String to, String message, java.util.Map<String, String> context)
    {
        return _iceI_sendMessageAsync(from, to, message, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param iceP_to -
     * @param iceP_message -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_sendMessageAsync(String iceP_from, String iceP_to, String iceP_message, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendMessage", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                     ostr.writeString(iceP_to);
                     ostr.writeString(iceP_message);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean sendGroupMessage(String from, String group, String message)
    {
        return sendGroupMessage(from, group, message, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean sendGroupMessage(String from, String group, String message, java.util.Map<String, String> context)
    {
        return _iceI_sendGroupMessageAsync(from, group, message, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> sendGroupMessageAsync(String from, String group, String message)
    {
        return _iceI_sendGroupMessageAsync(from, group, message, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> sendGroupMessageAsync(String from, String group, String message, java.util.Map<String, String> context)
    {
        return _iceI_sendGroupMessageAsync(from, group, message, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param iceP_group -
     * @param iceP_message -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_sendGroupMessageAsync(String iceP_from, String iceP_group, String iceP_message, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendGroupMessage", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                     ostr.writeString(iceP_group);
                     ostr.writeString(iceP_message);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default MessageDTO[] getHistory()
    {
        return getHistory(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default MessageDTO[] getHistory(java.util.Map<String, String> context)
    {
        return _iceI_getHistoryAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<MessageDTO[]> getHistoryAsync()
    {
        return _iceI_getHistoryAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<MessageDTO[]> getHistoryAsync(java.util.Map<String, String> context)
    {
        return _iceI_getHistoryAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<MessageDTO[]> _iceI_getHistoryAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<MessageDTO[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getHistory", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     MessageDTO[] ret;
                     ret = MessageListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default UserDTO[] getConnectedUsers()
    {
        return getConnectedUsers(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default UserDTO[] getConnectedUsers(java.util.Map<String, String> context)
    {
        return _iceI_getConnectedUsersAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<UserDTO[]> getConnectedUsersAsync()
    {
        return _iceI_getConnectedUsersAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<UserDTO[]> getConnectedUsersAsync(java.util.Map<String, String> context)
    {
        return _iceI_getConnectedUsersAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<UserDTO[]> _iceI_getConnectedUsersAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<UserDTO[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getConnectedUsers", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     UserDTO[] ret;
                     ret = UserListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default boolean registerUser(String username)
    {
        return registerUser(username, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean registerUser(String username, java.util.Map<String, String> context)
    {
        return _iceI_registerUserAsync(username, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> registerUserAsync(String username)
    {
        return _iceI_registerUserAsync(username, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> registerUserAsync(String username, java.util.Map<String, String> context)
    {
        return _iceI_registerUserAsync(username, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_registerUserAsync(String iceP_username, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "registerUser", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ChatServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ChatServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ChatServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ChatServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ChatServicePrx ice_adapterId(String newAdapterId)
    {
        return (ChatServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ChatServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ChatServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ChatServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ChatServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ChatServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (ChatServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ChatServicePrx ice_connectionCached(boolean newCache)
    {
        return (ChatServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ChatServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ChatServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatServicePrx ice_secure(boolean b)
    {
        return (ChatServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ChatServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ChatServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatServicePrx ice_preferSecure(boolean b)
    {
        return (ChatServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ChatServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ChatServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ChatServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ChatServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ChatServicePrx ice_collocationOptimized(boolean b)
    {
        return (ChatServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ChatServicePrx ice_twoway()
    {
        return (ChatServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ChatServicePrx ice_oneway()
    {
        return (ChatServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ChatServicePrx ice_batchOneway()
    {
        return (ChatServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ChatServicePrx ice_datagram()
    {
        return (ChatServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ChatServicePrx ice_batchDatagram()
    {
        return (ChatServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ChatServicePrx ice_compress(boolean co)
    {
        return (ChatServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ChatServicePrx ice_timeout(int t)
    {
        return (ChatServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ChatServicePrx ice_connectionId(String connectionId)
    {
        return (ChatServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ChatServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ChatServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Chat::ChatService";
    }
}
