//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public interface Observer extends com.zeroc.Ice.Object
{
    void notifyNewMessage(MessageDTO msg, com.zeroc.Ice.Current current);

    void notifyUserConnected(String username, com.zeroc.Ice.Current current);

    void notifyUserDisconnected(String username, com.zeroc.Ice.Current current);

    void notifyGroupCreated(GroupDTO group, com.zeroc.Ice.Current current);

    void notifyCallChunk(CallChunk chunk, com.zeroc.Ice.Current current);

    void notifyCallStarted(String from, String to, com.zeroc.Ice.Current current);

    void notifyCallStopped(String from, String to, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Chat::Observer",
        "::Ice::Object"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::Chat::Observer";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_notifyNewMessage(Observer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        MessageDTO iceP_msg;
        iceP_msg = MessageDTO.ice_read(istr);
        inS.endReadParams();
        obj.notifyNewMessage(iceP_msg, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_notifyUserConnected(Observer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_username;
        iceP_username = istr.readString();
        inS.endReadParams();
        obj.notifyUserConnected(iceP_username, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_notifyUserDisconnected(Observer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_username;
        iceP_username = istr.readString();
        inS.endReadParams();
        obj.notifyUserDisconnected(iceP_username, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_notifyGroupCreated(Observer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        GroupDTO iceP_group;
        iceP_group = GroupDTO.ice_read(istr);
        inS.endReadParams();
        obj.notifyGroupCreated(iceP_group, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_notifyCallChunk(Observer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        CallChunk iceP_chunk;
        iceP_chunk = CallChunk.ice_read(istr);
        inS.endReadParams();
        obj.notifyCallChunk(iceP_chunk, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_notifyCallStarted(Observer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        String iceP_to;
        iceP_from = istr.readString();
        iceP_to = istr.readString();
        inS.endReadParams();
        obj.notifyCallStarted(iceP_from, iceP_to, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_notifyCallStopped(Observer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_from;
        String iceP_to;
        iceP_from = istr.readString();
        iceP_to = istr.readString();
        inS.endReadParams();
        obj.notifyCallStopped(iceP_from, iceP_to, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "notifyCallChunk",
        "notifyCallStarted",
        "notifyCallStopped",
        "notifyGroupCreated",
        "notifyNewMessage",
        "notifyUserConnected",
        "notifyUserDisconnected"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 1:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 2:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 3:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 4:
            {
                return _iceD_notifyCallChunk(this, in, current);
            }
            case 5:
            {
                return _iceD_notifyCallStarted(this, in, current);
            }
            case 6:
            {
                return _iceD_notifyCallStopped(this, in, current);
            }
            case 7:
            {
                return _iceD_notifyGroupCreated(this, in, current);
            }
            case 8:
            {
                return _iceD_notifyNewMessage(this, in, current);
            }
            case 9:
            {
                return _iceD_notifyUserConnected(this, in, current);
            }
            case 10:
            {
                return _iceD_notifyUserDisconnected(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
