//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public interface ObserverPrx extends com.zeroc.Ice.ObjectPrx
{
    default void notifyNewMessage(MessageDTO msg)
    {
        notifyNewMessage(msg, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void notifyNewMessage(MessageDTO msg, java.util.Map<String, String> context)
    {
        _iceI_notifyNewMessageAsync(msg, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> notifyNewMessageAsync(MessageDTO msg)
    {
        return _iceI_notifyNewMessageAsync(msg, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> notifyNewMessageAsync(MessageDTO msg, java.util.Map<String, String> context)
    {
        return _iceI_notifyNewMessageAsync(msg, context, false);
    }

    /**
     * @hidden
     * @param iceP_msg -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_notifyNewMessageAsync(MessageDTO iceP_msg, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "notifyNewMessage", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     MessageDTO.ice_write(ostr, iceP_msg);
                 }, null);
        return f;
    }

    default void notifyUserConnected(String username)
    {
        notifyUserConnected(username, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void notifyUserConnected(String username, java.util.Map<String, String> context)
    {
        _iceI_notifyUserConnectedAsync(username, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> notifyUserConnectedAsync(String username)
    {
        return _iceI_notifyUserConnectedAsync(username, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> notifyUserConnectedAsync(String username, java.util.Map<String, String> context)
    {
        return _iceI_notifyUserConnectedAsync(username, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_notifyUserConnectedAsync(String iceP_username, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "notifyUserConnected", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                 }, null);
        return f;
    }

    default void notifyUserDisconnected(String username)
    {
        notifyUserDisconnected(username, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void notifyUserDisconnected(String username, java.util.Map<String, String> context)
    {
        _iceI_notifyUserDisconnectedAsync(username, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> notifyUserDisconnectedAsync(String username)
    {
        return _iceI_notifyUserDisconnectedAsync(username, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> notifyUserDisconnectedAsync(String username, java.util.Map<String, String> context)
    {
        return _iceI_notifyUserDisconnectedAsync(username, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_notifyUserDisconnectedAsync(String iceP_username, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "notifyUserDisconnected", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                 }, null);
        return f;
    }

    default void notifyGroupCreated(GroupDTO group)
    {
        notifyGroupCreated(group, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void notifyGroupCreated(GroupDTO group, java.util.Map<String, String> context)
    {
        _iceI_notifyGroupCreatedAsync(group, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> notifyGroupCreatedAsync(GroupDTO group)
    {
        return _iceI_notifyGroupCreatedAsync(group, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> notifyGroupCreatedAsync(GroupDTO group, java.util.Map<String, String> context)
    {
        return _iceI_notifyGroupCreatedAsync(group, context, false);
    }

    /**
     * @hidden
     * @param iceP_group -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_notifyGroupCreatedAsync(GroupDTO iceP_group, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "notifyGroupCreated", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     GroupDTO.ice_write(ostr, iceP_group);
                 }, null);
        return f;
    }

    default void notifyCallChunk(CallChunk chunk)
    {
        notifyCallChunk(chunk, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void notifyCallChunk(CallChunk chunk, java.util.Map<String, String> context)
    {
        _iceI_notifyCallChunkAsync(chunk, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> notifyCallChunkAsync(CallChunk chunk)
    {
        return _iceI_notifyCallChunkAsync(chunk, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> notifyCallChunkAsync(CallChunk chunk, java.util.Map<String, String> context)
    {
        return _iceI_notifyCallChunkAsync(chunk, context, false);
    }

    /**
     * @hidden
     * @param iceP_chunk -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_notifyCallChunkAsync(CallChunk iceP_chunk, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "notifyCallChunk", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     CallChunk.ice_write(ostr, iceP_chunk);
                 }, null);
        return f;
    }

    default void notifyCallStarted(String from, String to)
    {
        notifyCallStarted(from, to, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void notifyCallStarted(String from, String to, java.util.Map<String, String> context)
    {
        _iceI_notifyCallStartedAsync(from, to, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> notifyCallStartedAsync(String from, String to)
    {
        return _iceI_notifyCallStartedAsync(from, to, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> notifyCallStartedAsync(String from, String to, java.util.Map<String, String> context)
    {
        return _iceI_notifyCallStartedAsync(from, to, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param iceP_to -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_notifyCallStartedAsync(String iceP_from, String iceP_to, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "notifyCallStarted", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                     ostr.writeString(iceP_to);
                 }, null);
        return f;
    }

    default void notifyCallStopped(String from, String to)
    {
        notifyCallStopped(from, to, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void notifyCallStopped(String from, String to, java.util.Map<String, String> context)
    {
        _iceI_notifyCallStoppedAsync(from, to, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> notifyCallStoppedAsync(String from, String to)
    {
        return _iceI_notifyCallStoppedAsync(from, to, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> notifyCallStoppedAsync(String from, String to, java.util.Map<String, String> context)
    {
        return _iceI_notifyCallStoppedAsync(from, to, context, false);
    }

    /**
     * @hidden
     * @param iceP_from -
     * @param iceP_to -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_notifyCallStoppedAsync(String iceP_from, String iceP_to, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "notifyCallStopped", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_from);
                     ostr.writeString(iceP_to);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ObserverPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ObserverPrx.class, _ObserverPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ObserverPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ObserverPrx.class, _ObserverPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ObserverPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ObserverPrx.class, _ObserverPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ObserverPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ObserverPrx.class, _ObserverPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ObserverPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ObserverPrx.class, _ObserverPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ObserverPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ObserverPrx.class, _ObserverPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ObserverPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ObserverPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ObserverPrx ice_adapterId(String newAdapterId)
    {
        return (ObserverPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ObserverPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ObserverPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ObserverPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ObserverPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ObserverPrx ice_invocationTimeout(int newTimeout)
    {
        return (ObserverPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ObserverPrx ice_connectionCached(boolean newCache)
    {
        return (ObserverPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ObserverPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ObserverPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ObserverPrx ice_secure(boolean b)
    {
        return (ObserverPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ObserverPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ObserverPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ObserverPrx ice_preferSecure(boolean b)
    {
        return (ObserverPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ObserverPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ObserverPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ObserverPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ObserverPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ObserverPrx ice_collocationOptimized(boolean b)
    {
        return (ObserverPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ObserverPrx ice_twoway()
    {
        return (ObserverPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ObserverPrx ice_oneway()
    {
        return (ObserverPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ObserverPrx ice_batchOneway()
    {
        return (ObserverPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ObserverPrx ice_datagram()
    {
        return (ObserverPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ObserverPrx ice_batchDatagram()
    {
        return (ObserverPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ObserverPrx ice_compress(boolean co)
    {
        return (ObserverPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ObserverPrx ice_timeout(int t)
    {
        return (ObserverPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ObserverPrx ice_connectionId(String connectionId)
    {
        return (ObserverPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ObserverPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ObserverPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Chat::Observer";
    }
}
