//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public class UserDTO implements java.lang.Cloneable,
                                java.io.Serializable
{
    public String username;

    public boolean online;

    public UserDTO()
    {
        this.username = "";
    }

    public UserDTO(String username, boolean online)
    {
        this.username = username;
        this.online = online;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        UserDTO r = null;
        if(rhs instanceof UserDTO)
        {
            r = (UserDTO)rhs;
        }

        if(r != null)
        {
            if(this.username != r.username)
            {
                if(this.username == null || r.username == null || !this.username.equals(r.username))
                {
                    return false;
                }
            }
            if(this.online != r.online)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Chat::UserDTO");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, username);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, online);
        return h_;
    }

    public UserDTO clone()
    {
        UserDTO c = null;
        try
        {
            c = (UserDTO)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.username);
        ostr.writeBool(this.online);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.username = istr.readString();
        this.online = istr.readBool();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, UserDTO v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public UserDTO ice_read(com.zeroc.Ice.InputStream istr)
    {
        UserDTO v = new UserDTO();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<UserDTO> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, UserDTO v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<UserDTO> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(UserDTO.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final UserDTO _nullMarshalValue = new UserDTO();

    /** @hidden */
    public static final long serialVersionUID = -816066398L;
}
